### ISSUE TITLE
Ice XI

### ISSUE THREAD

**Issue by mberrens** [vitroid/GenIce#16]
Hello,

I am attempting to generate a few Ice XI configurations (out of the 16 candidates) however the only 'type' option for ferroelectric Ice XI is '11i' which only provides me with one of the sixteen candidates for Ice XI. I am wondering if there is a way for me to specify which of the 16 candidates I would like. Any help would be greatly appreciated.

**Comment by vitroid** [comment]
Sorry for inconvenience. As GenIce is designed for generating hydrogen-disordered ices, the choice of hydrogen-ordered ices is limited. Do you have CIF files for the 16 types? Or where do you find that there are only 16 possibilities for ice XI?

**Comment by mberrens** [comment]
I found it from the GenIce 2 ReadMe under 'Usage' section:  " 11i      Sixteen candidates for Ice XI' ".  But additionally this work (https://doi.org/10.1021/jp048434u) finds 16 possible candidates. This paper also includes the coordinates for each of the configurations. If it is not possible, that is no problem, I was just confused as to which candidate was being produced when I use the 11i type.

**Comment by vitroid** [comment]
Alright, I understand. `genice2 11i[3]` would generate the third type. If you omit the options in the bracket, it will make the first type. Note that some shells may require quotations to use brackets. `genice2 "11i[3]"`.

**Comment by mberrens** [comment]
Great thank you!
