### ISSUE TITLE
Missing guest molecules in sH structure

### ISSUE THREAD

**Issue by eszter137** [vitroid/GenIce#4]
Hi,

it seems the sH clathrate structure doesn't include the cages information in `genice/lattices/sH.py` so it won't have guest molecules in the generated structure.
(This was my command line:
`genice --rep 2 2 2 --seed 0 --format=exyz --water tip3p -g 12=ch4 sH`)

I was wondering if the information for the cages could be added.

Many thanks,
Eszter

**Comment by vitroid** [comment]
Thank you very much for your report.

sH.py has been updated to include cage information in the develop branch, but it was not reflected in the master. The new sH.py is now included in the latest GenIce.  Update it with the pip command.

**Comment by eszter137** [comment]
Thank you very much!
Sorry, it is strange but it seems there might have been a problem with the commit: the page https://github.com/vitroid/GenIce/tree/master/genice/lattices shows that it is the `DOH.py` that changed 4 hours ago with the commit and the latest change for `sH.py` was 3 years ago.

**Comment by vitroid** [comment]
It is ok. sH.py is actually a link file (aka alias) to DOH.py. The name "DOH" comes from the Zeolite database. The structures of clathrate hydrate type H and zeolite DOH are topologically identical.

**Comment by vitroid** [comment]
Here are data for DOH: https://asia.iza-structure.org/IZA-SC/framework.php?STC=DOH

**Comment by eszter137** [comment]
Apologies, it was me messing up - it seems I had 2 versions of genice (because of having one pip in the conda environment and one outside) and it seems I updated the one that was not the default for the `genice` command. Now I uninstalled the other one and it works fine.
Thank you very much again!
