### ISSUE TITLE
Ice 3 depolarization stuck

### ISSUE THREAD

**Issue by torbsorensen** [vitroid/GenIce#5]
Hello there, a very nice and helpful programme you have made, thank you!

I'm not sure whether there is a fundamental reason behind it, but when I'm trying to produce a single ice 3 structure using "genice ice3 > test.gro" it gets stuck at "INFO   Net polarization: [0.00 -0.00 2.00]". It's working fine when I include '--rep 2 2 2' or '--rep 3 3 3'. If there is a fundamental reason behind it, I guess it would be useful with a warning like on ice 7 and 8, when trying to produce a single cell. I've attached the output at the bottom FYI.

Thanks a lot!
//Tor

genice ice3 > test.gro
INFO Load lattice module 'ice3', arguments []
INFO   
INFO   Command line: /anaconda3/bin/genice ice3
INFO No rotmatrices in lattice
INFO Cell dimension:
INFO   a = 6.666
INFO   b = 6.666
INFO   c = 6.936
INFO   A = 90.0
INFO   B = 90.0
INFO   C = 90.0
INFO HB connectivity is not defined.
INFO Bond length (specified): 3.0
INFO Target Density: 1.165
INFO Original Density: 0.0011637864512692793
INFO Bond length (scaled, nm): 0.2998957965366282
INFO Load format module 'gromacs', arguments []
INFO Stage1: Replication.
INFO   Number of water molecules: 12
INFO   Pairs are not given explicitly.
INFO   Estimating the bonds according to the pair distances.
INFO   Number of water nodes: 12
INFO Cell dimension:
INFO   a = 0.6663684599043879
INFO   b = 0.6663684599043879
INFO   c = 0.6933590815926843
INFO   A = 90.0
INFO   B = 90.0
INFO   C = 90.0
INFO Stage1: end.
INFO Stage2: Graph preparation.
INFO   Number of pre-oriented hydrogen bonds: 0
INFO   Number of unoriented hydrogen bonds: 24
INFO   Number of hydrogen bonds: 24 (regular num: 24)
INFO Stage2: end.
INFO Stage3: Bernal-Fowler rule.
INFO   Defects remaining: 11
INFO   Defects remaining: 8
INFO   Defects remaining: 4
INFO   Defects remaining: 2
INFO   Defects remaining: 1
INFO   Defects remaining: 0
INFO Stage3: end.
INFO Stage4: Depolarization.
INFO   Non Z4: []
INFO   Net polarization: [-2.00 2.00 2.00]
INFO   Net polarization: [0.00 2.00 2.00]
INFO   Net polarization: [0.00 -0.00 2.00]
^CTraceback (most recent call last):
  File "/anaconda3/bin/genice", line 8, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/genice/__main__.py", line 114, in main
    depolarize=depolarize,
  File "/anaconda3/lib/python3.6/site-packages/genice/genice.py", line 765, in generate_ice
    record_depolarization_path=record_depolarization_path)
  File "/anaconda3/lib/python3.6/site-packages/genice/genice.py", line 959, in stage4
    dg.depolarize(self.spacegraph, self.repcell.mat, draw=None)
  File "/anaconda3/lib/python3.6/site-packages/genice/digraph.py", line 501, in depolarize
    cycle = traversing_cycle(spaceicegraph, cell, axis, draw)
  File "/anaconda3/lib/python3.6/site-packages/genice/digraph.py", line 405, in traversing_cycle
    logger.debug("Dipole of the path2: {0}".format(spaceicegraph.dipole_moment(path2)))
  File "/anaconda3/lib/python3.6/site-packages/genice/digraph.py", line 319, in dipole_moment
    for i in range(len(order) - 1):
KeyboardInterrupt
INFO Completed.

**Comment by vitroid** [comment]
Thank you for your feedback. Your advice is very helpful. We'll address this in the next update so that it doesn't get stuck in an infinite loop.

This may be due to the use of the steepest descent optimization to remove net polarization. It works fine unless the cells are too small, try changing the random seed with the -s option.

**Comment by vitroid** [comment]
I am preparing an update for this issue in the next major upgrade of GenIce. Sorry for inconvenience.
