### ISSUE TITLE
Missing guest molecules in filled ices

### ISSUE THREAD

**Issue by eszter137** [vitroid/GenIce#6]
Hi,

I would like to generate filled ices with the code (especially the filled ice Ih structure) and it seems to me that the filled ices (C0, C1, C2, STprime) miss the guest molecule's cages in the code.

I was wondering if the cages of the filled ices and the filled ice Ih structure could be added.

Thank you very much.
Best wishes,
Eszter

**Comment by vitroid** [comment]
Thank you for your advice. These have a channel, not a cage, so the cage information is missing. However, it might be useful to know the approximate location of the guest molecule as well. I will look it up.

**Comment by eszter137** [comment]
Thank you very much.

**Comment by eszter137** [comment]
Meanwhile, I found the structure with the guest molecules' position in the supplementary material of a paper so it is not important for me at the moment. I'll just copy it here in case it's useful: https://aip.scitation.org/doi/suppl/10.1063/1.4933371 .

**Comment by vitroid** [comment]
Thank you very much. The data are very useful to make the plugins.

**Comment by vitroid** [comment]
In a quick response, ice1hte and c0te (te means Teeratchanan) have been added to the cif branch of GenIce. Other crystal types will be added in the branch soon.

**Comment by eszter137** [comment]
Thank you very much! (It seems to me that it isn't on the master branch yet.)

**Comment by vitroid** [comment]
Merged into master branch and registered to PyPI as version 1.0.10. Now they are available via pip. Thank you!
