### ISSUE TITLE
bug:when generating 6site-ice ,the structual of water molecule is wrong 

### ISSUE THREAD

**Issue by YueCuiyi** [vitroid/GenIce#8]
bug:when generating 6site-ice ,the structual of water molecule is wrong
usage:       genice --water 6site --format g Ih > 6siteIh16.gro

I found the distance between O and other atom in the same 6site-water molecule is ten times that of correct one.

**Comment by vitroid** [comment]
Thank you very much! I fixed the bug and released as v1.0.11.

**Comment by vitroid** [comment]
Now the bug is also fixed in master branch.
