### ISSUE TITLE
Coordinates Swapped When Generating Ih Gro file

### ISSUE THREAD

**Issue by mberrens** [vitroid/GenIce#9]
When generating a .gro file of an Ih ice slab with a tip4p water model using genice the coordinates system were switched around such that what was x should be y what was y should be z and what was z should be x. 

Using this exact code in Colab:
from genice2.genice import GenIce
from genice2.plugin import Lattice, Format, Molecule

lattice    = Lattice("Ih") 
formatter  = Format("gromacs")
water      = Molecule("tip4p")
ice = GenIce(lattice, rep=[8,8,6]).generate_ice(water, formatter)
print(ice)

Visualizing this file in VMD the basal facet (which should be in the z direction) was in the y direction

**Comment by vitroid** [comment]
You are right. That is the oldest structure we made by hand, and therefore the axes are not correct.

I update the GenIce2 on PyPI repository (2.1b4). Please re-install it via pip command, and specify "1h_unit" instead of "1h".

**Comment by vitroid** [comment]
New sample code for Colab includes the structure of 1h_unit rendered with py3dmol.

**Comment by mberrens** [comment]
great, thanks so much!
